/// RoverClientError represents all possible failures that can occur during a client request.
#[derive(thiserror::Error, Debug)]
pub enum RoverClientError {
    /// Encountered an error handling the received response.
    #[error("{msg}")]
    AdhocError {
        /// The error message.
        msg: String,
    },

    /// Encountered errors while converting a persisted query manifest generated by the Relay compiler to the structure
    /// required by Apollo GraphOS
    #[error(
        "The persisted query manifest generated by the Relay compiler contained the following errors:\n\n{errors}"
    )]
    RelayOperationParseFailures { errors: String },
}
